// Real BIND zone generation, mirroring ftpService.js/mailService.js's
// structure and reasoning (see ftpService.js's top-of-file comment for
// the fuller version). Until this file existed, dns_records was pure
// CRUD with zero effect on actual DNS resolution — no code anywhere
// wrote a zone file, validated one, or told a nameserver to reload.
//
// This module writes a real BIND-format zone file per domain plus one
// generated conf snippet declaring every zone this app manages, and
// best-effort validates (named-checkzone) and applies (rndc) it. What it
// deliberately does NOT touch is the operator's real named.conf(.local) —
// same reasoning as vsftpd.conf/PAM and Postfix's main.cf: it needs one
// line, added once by the operator, including the generated snippet this
// module rewrites on every DNS change. See getSetupInstructions().
const fs = require('fs').promises;
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');
const config = require('../config/config');
const logger = require('../config/logger');

const execFileAsync = promisify(execFile);

const DNS_CONFIG_DIR = path.join(config.PATHS.CONFIGS, 'dns');
const ZONES_DIR = path.join(DNS_CONFIG_DIR, 'zones');
const ZONES_INCLUDE_FILE = path.join(DNS_CONFIG_DIR, 'zones.conf');

let bindSupportCache = null;

async function detectBindSupport() {
  if (bindSupportCache !== null) return bindSupportCache;
  if (config.SYSTEM.IS_WINDOWS) {
    bindSupportCache = { available: false, reason: 'BIND integration is Linux-only' };
    return bindSupportCache;
  }
  try {
    await execFileAsync('which', ['named']);
  } catch {
    bindSupportCache = { available: false, reason: 'BIND (named) is not installed on this host' };
    return bindSupportCache;
  }
  try {
    await execFileAsync('which', ['named-checkzone']);
  } catch {
    bindSupportCache = { available: false, reason: 'named is installed but named-checkzone (bind-utils) was not found' };
    return bindSupportCache;
  }
  bindSupportCache = { available: true };
  return bindSupportCache;
}

// A record's `name` column is stored as a full FQDN (see domains.js's
// default-records insert: "domain" for the apex, "www.<domain>" for
// www, ...) — BIND zone files instead use names relative to the zone
// (bare "@" for the apex, "www" for a subdomain), so this converts one to
// the other rather than requiring the caller/DB to store both.
function relativizeName(name, domain) {
  if (name === domain) return '@';
  if (name.endsWith(`.${domain}`)) return name.slice(0, -(domain.length + 1));
  return `${name}.`; // not actually under this zone — write it fully-qualified rather than guess wrong
}

// BIND zone serials must be a 32-bit unsigned int that increases on every
// change a secondary should notice; a Unix timestamp satisfies both
// (monotonic across syncs, fits comfortably until year 2106) without this
// app needing to track a separate per-zone counter.
function nextSerial() {
  return Math.floor(Date.now() / 1000);
}

function generateZoneFile(domain, records) {
  const ttl = 3600;
  const serial = nextSerial();
  const lines = [
    `; Generated by ServerPanel Pro for ${domain} — do not edit by hand, changes are overwritten on the next DNS record change.`,
    `$TTL ${ttl}`,
    `@\tIN\tSOA\tns1.${domain}. hostmaster.${domain}. (`,
    `\t\t\t${serial}\t; serial`,
    `\t\t\t3600\t\t; refresh`,
    `\t\t\t900\t\t; retry`,
    `\t\t\t1209600\t\t; expire`,
    `\t\t\t3600 )\t\t; minimum`,
    ''
  ];

  const nsRecords = records.filter(r => r.type === 'NS');
  if (nsRecords.length === 0) {
    lines.push(`@\tIN\tNS\tns1.${domain}.`);
  }

  for (const record of records) {
    const name = relativizeName(record.name, domain);
    const recTtl = record.ttl || ttl;
    if (record.type === 'MX') {
      lines.push(`${name}\t${recTtl}\tIN\tMX\t${record.priority || 10}\t${record.value}`);
    } else if (record.type === 'SRV') {
      // dns_records has no separate weight/port columns — value is
      // expected to carry "weight port target" after the stored priority.
      lines.push(`${name}\t${recTtl}\tIN\tSRV\t${record.priority || 0}\t${record.value}`);
    } else if (record.type === 'TXT') {
      lines.push(`${name}\t${recTtl}\tIN\tTXT\t"${String(record.value).replace(/"/g, '\\"')}"`);
    } else {
      lines.push(`${name}\t${recTtl}\tIN\t${record.type}\t${record.value}`);
    }
  }

  return lines.join('\n') + '\n';
}

// Writes domain's zone file, validates it (best-effort, only when
// named-checkzone is available), rewrites the include conf listing every
// zone this app manages, and best-effort tells BIND to pick it up.
// Returns { activated, reason } like ftpService/mailService's sync
// functions — the app's own dns_records rows are already saved by the
// caller regardless of what this returns.
async function syncBindZone(domain, records) {
  const support = await detectBindSupport();
  if (!support.available) {
    return { activated: false, reason: support.reason };
  }

  try {
    await fs.mkdir(ZONES_DIR, { recursive: true });
    const zoneFilePath = path.join(ZONES_DIR, `${domain}.zone`);
    await fs.writeFile(zoneFilePath, generateZoneFile(domain, records));

    try {
      await execFileAsync('named-checkzone', [domain, zoneFilePath]);
    } catch (checkError) {
      return { activated: false, reason: `Generated zone failed named-checkzone: ${checkError.message}` };
    }

    // Rebuild the include conf from every zone file actually on disk, not
    // just this one — mirrors ftpService's "rewrite everything from
    // current state" pattern rather than trying to patch one block in
    // place.
    const zoneFiles = (await fs.readdir(ZONES_DIR)).filter(f => f.endsWith('.zone'));
    const confBlocks = zoneFiles.map(f => {
      const zoneDomain = f.slice(0, -'.zone'.length);
      return `zone "${zoneDomain}" {\n\ttype master;\n\tfile "${path.join(ZONES_DIR, f)}";\n};`;
    });
    await fs.writeFile(ZONES_INCLUDE_FILE, confBlocks.join('\n\n') + '\n');

    // rndc reconfig picks up newly-added zone{} blocks; rndc reload
    // <domain> forces this specific zone's file to be re-read even if it
    // was already declared. Both are best-effort — a host where the
    // operator hasn't yet added the one-time named.conf include (see
    // getSetupInstructions) will fail rndc reconfig harmlessly here.
    await execFileAsync('rndc', ['reconfig']).catch(err =>
      logger.warn(`DNS: rndc reconfig failed for ${domain} (zone file was still written) :`, err.message));
    await execFileAsync('rndc', ['reload', domain]).catch(() => { /* expected to fail until the operator's one-time named.conf include is in place */ });

    return { activated: true };
  } catch (error) {
    logger.warn(`DNS: zone sync failed for ${domain}, records still saved in the app:`, error.message);
    return { activated: false, reason: `zone sync failed: ${error.message}` };
  }
}

// One-time manual configuration an operator needs to apply to named.conf
// (or named.conf.local, on distros that split it that way) for the zones
// this module generates to actually be served — intentionally never
// applied automatically (see the top-of-file comment).
function getSetupInstructions() {
  return {
    namedConfLines: [
      `include "${ZONES_INCLUDE_FILE}";`
    ],
    note: 'Add this single include line to your real named.conf (or named.conf.local, if your distro splits it that way) once, then run `rndc reconfig`. Every domain\'s zone this app manages is declared inside the included file — no further per-domain edits to named.conf are needed. Confirm with `named-checkconf` and test with `dig @localhost <domain>` after applying it.'
  };
}

module.exports = {
  detectBindSupport,
  generateZoneFile,
  syncBindZone,
  getSetupInstructions,
  relativizeName
};
